simplify_next_week:
  use_abbreviated: false
  today: Heute
  tomorrow: Morgen

weekdays_abbr:
  0: Mo
  1: Di
  2: Mi
  3: Do
  4: Fr
  5: Sa
  6: So

weekdays_full:
  0: Montag
  1: Dienstag
  2: Mittwoch
  3: Donnerstag
  4: Freitag
  5: Samstag
  6: Sonntag

months_abbr:
  1: Jan
  2: Feb
  3: Mär
  4: Apr
  5: Mai
  6: Jun
  7: Jul
  8: Aug
  9: Sep
  10: Okt
  11: Nov
  12: Dez

months_full:
  1: Januar
  2: Februar
  3: März
  4: April
  5: Mai
  6: Juni
  7: Juli
  8: August
  9: September
  10: Oktober
  11: November
  12: Dezember