simplify_next_week:
  use_abbreviated: false
  today: Oggi
  tomorrow: Domani

weekdays_abbr:
  0: Lun
  1: Mar
  2: Mer
  3: Gio
  4: Ven
  5: Sab
  6: Dom

weekdays_full:
  0: Lunedì
  1: Martedì
  2: Mercoledì
  3: Giovedì
  4: Venerdì
  5: Sabato
  6: Domenica

months_abbr:
  1: Gen
  2: Feb
  3: Mar
  4: Apr
  5: Mag
  6: Giu
  7: Lug
  8: Ago
  9: Set
  10: Ott
  11: Nov
  12: Dic

months_full:
  1: Gennaio
  2: Febbraio
  3: Marzo
  4: Aprile
  5: Maggio
  6: Giugno
  7: Luglio
  8: Agosto
  9: Settembre
  10: Ottobre
  11: Novembre
  12: Dicembre