simplify_next_week:
  use_abbreviated: false
  today: Сегодня
  tomorrow: Завтра

weekdays_abbr:
  0: Пн
  1: Вт
  2: Ср
  3: Чт
  4: Пт
  5: Сб
  6: Вс

weekdays_full:
  0: Понедельник
  1: Вторник
  2: Среда
  3: Четверг
  4: Пятница
  5: Суббота
  6: Воскресенье

months_abbr:
  1: Янв
  2: Фев
  3: Мар
  4: Апр
  5: Май
  6: Июн
  7: Июл
  8: Авг
  9: Сен
  10: Окт
  11: Ноя
  12: Дек

months_full:
  1: Январь
  2: Февраль
  3: Март
  4: Апрель
  5: Май
  6: Июнь
  7: Июль
  8: Август
  9: Сентябрь
  10: Октябрь
  11: Ноябрь
  12: Декабрь