################################################################################
##########                         GENERAL:                           ##########
################################################################################
movies: 2 #0 = Don't process, 1 = Download trailers with yt-dlp, 2 = Use placeholder video file
tv: 1 #0 = Don't process, 1 = Download trailers with yt-dlp, 2 = Use placeholder video file
utc_offset: +1
debug: false
cleanup: true

skip_channels:
  - "Starlight Cinema"
  - "fake trailers"
  - "Black And White Media"
  - "CircleX Creations"
  - "New Movie Updates"

################################################################################
##########                         MOVIES:                            ##########
################################################################################
future_days_upcoming_movies: 30
include_inCinemas: false
future_only: false
exclude_radarr_tags: exclude, private

################################################################################
##########                         TV SHOWS:                          ##########
################################################################################
future_days_upcoming_shows: 30
recent_days_new_show: 7
exclude_sonarr_tags: exclude, private
  
################################################################################
##########                   RADARR CONFIGURATION:                    ##########
################################################################################
radarr_url: 'http://localhost:7878'
radarr_api_key: 'YOUR_RADARR_API_KEY'

 
################################################################################
##########                   SONARR CONFIGURATION:                    ##########
################################################################################
sonarr_url: 'http://localhost:8989'
sonarr_api_key: 'YOUR_SONARR_API_KEY'

################################################################################
##########                UPCOMING MOVIES COLLECTION:                 ##########
################################################################################
collection_upcoming_movies:
  collection_name: "ComingSoon"
  item_label: Coming Soon
  non_item_remove_label: Coming Soon
  build_collection: false

################################################################################
##########              UPCOMING MOVIES OVERLAY FUTURE:               ##########
################################################################################  
backdrop_upcoming_movies_future:
  enable: true
  name: red_frame
  url: https://raw.githubusercontent.com/netplexflix/Upcoming-Movies-for-Kometa/refs/heads/main/config/overlays/red_frame.png

text_upcoming_movies_future:
  use_text: "EXPECTED"
  date_format: "d mmm"
  capitalize_dates: true
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: top
  vertical_offset: 20
  font_size: 70
  font_color: "#FFFFFF"

################################################################################
##########             UPCOMING MOVIES OVERLAY RELEASED:              ##########
################################################################################  
backdrop_upcoming_movies_released:
  enable: false
  name: red_frame
  url: https://raw.githubusercontent.com/netplexflix/Upcoming-Movies-for-Kometa/refs/heads/main/config/overlays/red_frame.png

text_upcoming_movies_released:
  file: config\overlays\red_frame.png
  use_text: "COMING SOON"
  date_format: "d mmm"
  capitalize_dates: true
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: top
  vertical_offset: 20
  font_size: 70
  font_color: "#FFFFFF"

################################################################################
##########                     UPCOMING SHOWS:                        ##########
################################################################################
collection_upcoming_shows:
  collection_name: "ComingSoon"
  item_label: Coming Soon
  non_item_remove_label: Coming Soon
  build_collection: false
  
backdrop_upcoming_shows:
  enable: true
  name: red_frame_bottom
  url: https://raw.githubusercontent.com/netplexflix/Upcoming-Movies-for-Kometa/refs/heads/main/config/overlays/red_frame_bottom.png

text_upcoming_shows:
  use_text: "PREMIERES"
  date_format: "d mmm"
  capitalize_dates: true
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 17
  font_size: 70
  font_color: "#FFFFFF"

################################################################################
##########                        NEW SHOWS:                          ##########
################################################################################
backdrop_new_show:
  enable: true
  back_color: "#EB3233"
  back_height: 90
  back_width: 950
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 20
  group: TSSK_backdrop
  weight: 50

text_new_show:
  use_text: "RECENTLY ADDED"
  horizontal_align: center
  horizontal_offset: 0
  vertical_align: bottom
  vertical_offset: 35
  font_size: 70
  font_color: "#FFFFFF"
  group: TSSK_text
  weight: 50